# load_testing/docker-compose.yml
version: '3.8'
services:
  fastapi:
    build:
      context: ../serving
    ports: ["8000:8000"]
    networks: [mlops-network]

  locust:
    image: locustio/locust:latest
    ports: ["8089:8089"]
    volumes: [./locust:/mnt/locust]
    command: -f /mnt/locust/locustfile.py --host=http://fastapi:8000 --master
    depends_on: [fastapi]
    networks: [mlops-network]

  locust_worker:
    image: locustio/locust:latest
    volumes: [./locust:/mnt/locust]
    command: -f /mnt/locust/locustfile.py --worker --master-host=locust
    depends_on: [locust]
    networks: [mlops-network]

  prometheus:
    image: prom/prometheus:latest
    ports: ["9090:9090"]
    volumes: [./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml]
    networks: [mlops-network]

  grafana:
    image: grafana/grafana:latest
    ports: ["3000:3000"]
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks: [mlops-network]

networks:
  mlops-network:
    driver: bridge